"use client";

import { useState } from "react";
import { Loader2, Sparkles } from "lucide-react";
import { useEditor } from "@/lib/store/editor";
import type { Layer, ReviewStatus } from "@/lib/types";

function NumField({
  label,
  value,
  onChange,
}: {
  label: string;
  value: number;
  onChange: (n: number) => void;
}) {
  return (
    <label className="flex items-center gap-2 text-xs">
      <span className="w-6 text-muted-foreground">{label}</span>
      <input
        type="number"
        value={Math.round(value)}
        onChange={(e) => onChange(Number(e.target.value) || 0)}
        className="w-full rounded-md border border-border bg-background px-2 py-1 font-mono text-xs tabular-nums outline-none focus:border-primary"
      />
    </label>
  );
}

const REVIEW: { id: ReviewStatus; label: string; cls: string }[] = [
  { id: "approved", label: "Approved", cls: "border-emerald-600 text-emerald-500" },
  { id: "needs_changes", label: "Needs Changes", cls: "border-amber-600 text-amber-500" },
  { id: "send_back", label: "Send Back", cls: "border-red-600 text-red-500" },
];

export function Inspector({
  onGenerate,
}: {
  onGenerate: (layer: Layer) => void;
}) {
  const layers = useEditor((s) => s.layers);
  const selectedId = useEditor((s) => s.selectedId);
  const updateLayer = useEditor((s) => s.updateLayer);
  const [tab, setTab] = useState<"inspector" | "layers">("inspector");

  const layer = layers.find((l) => l.id === selectedId) ?? null;

  return (
    <aside className="flex w-72 shrink-0 flex-col border-l border-border">
      <div className="flex border-b border-border">
        {(["inspector", "layers"] as const).map((t) => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className={`flex-1 px-3 py-2 text-xs capitalize transition-colors ${
              tab === t
                ? "border-b-2 border-primary text-foreground"
                : "text-muted-foreground hover:text-foreground"
            }`}
          >
            {t}
          </button>
        ))}
      </div>

      {tab === "layers" ? (
        <div className="flex-1 overflow-y-auto p-2">
          {layers.length === 0 && (
            <p className="p-2 text-xs text-muted-foreground">No layers yet.</p>
          )}
          {[...layers]
            .sort((a, b) => b.z_index - a.z_index)
            .map((l) => (
              <button
                key={l.id}
                onClick={() => useEditor.getState().select(l.id)}
                className={`flex w-full items-center justify-between rounded-md px-2 py-1.5 text-left text-xs ${
                  l.id === selectedId
                    ? "bg-primary/15 text-primary"
                    : "text-muted-foreground hover:bg-muted hover:text-foreground"
                }`}
              >
                <span className="capitalize">{l.kind}</span>
                <span className="opacity-60">{l.geometry.w}×{l.geometry.h}</span>
              </button>
            ))}
        </div>
      ) : !layer ? (
        <p className="p-4 text-xs text-muted-foreground">
          Select a layer to edit its properties, or pick the Panel tool and drag
          on the page to create one.
        </p>
      ) : (
        <div className="flex-1 space-y-4 overflow-y-auto p-3">
          <div className="flex items-center justify-between">
            <span className="text-sm font-medium capitalize">{layer.kind}</span>
            {layer.last_provider && layer.last_provider !== "gemini" && (
              <span
                title="Generated by a fallback provider — character consistency may drift. Worth a closer review."
                className="rounded border border-amber-600 px-1.5 py-0.5 text-[10px] text-amber-500"
              >
                {layer.last_provider}
              </span>
            )}
          </div>

          <section className="space-y-2">
            <p className="text-[10px] tracking-wide text-muted-foreground">GEOMETRY</p>
            <div className="grid grid-cols-2 gap-2">
              <NumField label="X" value={layer.geometry.x}
                onChange={(n) => updateLayer(layer.id, { geometry: { ...layer.geometry, x: n } })} />
              <NumField label="Y" value={layer.geometry.y}
                onChange={(n) => updateLayer(layer.id, { geometry: { ...layer.geometry, y: n } })} />
              <NumField label="W" value={layer.geometry.w}
                onChange={(n) => updateLayer(layer.id, { geometry: { ...layer.geometry, w: n } })} />
              <NumField label="H" value={layer.geometry.h}
                onChange={(n) => updateLayer(layer.id, { geometry: { ...layer.geometry, h: n } })} />
            </div>
            <NumField label="↻" value={layer.geometry.rotation}
              onChange={(n) => updateLayer(layer.id, { geometry: { ...layer.geometry, rotation: n } })} />
          </section>

          <section className="space-y-2">
            <p className="text-[10px] tracking-wide text-muted-foreground">STYLE</p>
            <label className="flex items-center gap-2 text-xs">
              <span className="w-14 text-muted-foreground">Border</span>
              <input type="number" value={layer.style.strokeWidth ?? 2}
                onChange={(e) => updateLayer(layer.id, { style: { ...layer.style, strokeWidth: Number(e.target.value) || 0 } })}
                className="w-full rounded-md border border-border bg-background px-2 py-1 font-mono text-xs tabular-nums outline-none focus:border-primary" />
            </label>
            <label className="flex items-center gap-2 text-xs">
              <span className="w-14 text-muted-foreground">Corner</span>
              <input type="number" value={layer.style.rx ?? 0}
                onChange={(e) => updateLayer(layer.id, { style: { ...layer.style, rx: Number(e.target.value) || 0 } })}
                className="w-full rounded-md border border-border bg-background px-2 py-1 font-mono text-xs tabular-nums outline-none focus:border-primary" />
            </label>
          </section>

          {(layer.kind === "text" || layer.kind === "sfx" || layer.kind === "bubble") && (
            <section className="space-y-2">
              <p className="text-[10px] tracking-wide text-muted-foreground">CONTENT</p>
              <textarea
                value={layer.content ?? ""}
                onChange={(e) => updateLayer(layer.id, { content: e.target.value }, true)}
                onBlur={() => useEditor.getState().commit()}
                rows={2}
                className="w-full resize-none rounded-md border border-border bg-background px-2 py-1 text-xs outline-none focus:border-primary"
              />
            </section>
          )}

          {layer.kind === "panel" && (
            <section className="space-y-2">
              <p className="text-[10px] tracking-wide text-muted-foreground">AI CONTENT</p>
              <textarea
                value={layer.prompt ?? ""}
                onChange={(e) => updateLayer(layer.id, { prompt: e.target.value }, true)}
                onBlur={() => useEditor.getState().commit()}
                rows={4}
                placeholder="Describe this panel…"
                className="w-full resize-none rounded-md border border-border bg-background px-2 py-1 text-xs outline-none focus:border-primary"
              />
              <button
                onClick={() => onGenerate(layer)}
                disabled={
                  !layer.prompt ||
                  layer.generation_status === "queued" ||
                  layer.generation_status === "generating"
                }
                className="flex w-full items-center justify-center gap-2 rounded-md bg-primary px-3 py-2 text-xs font-medium text-primary-foreground disabled:opacity-40"
              >
                {layer.generation_status === "queued" ||
                layer.generation_status === "generating" ? (
                  <>
                    <Loader2 className="size-3.5 animate-spin" />
                    {layer.generation_status === "queued" ? "Queued…" : "Generating…"}
                  </>
                ) : (
                  <>
                    <Sparkles className="size-3.5" />
                    Generate Panel
                  </>
                )}
              </button>
              {layer.generation_status === "failed" && (
                <p className="text-[11px] text-red-500">
                  Generation failed. Try again or adjust the prompt.
                </p>
              )}
            </section>
          )}

          <section className="space-y-2">
            <p className="text-[10px] tracking-wide text-muted-foreground">REVIEW STATUS</p>
            <div className="flex flex-wrap gap-1.5">
              {REVIEW.map((r) => (
                <button
                  key={r.id}
                  onClick={() =>
                    updateLayer(layer.id, {
                      review_status: layer.review_status === r.id ? "pending" : r.id,
                    })
                  }
                  className={`rounded-md border px-2 py-1 text-[11px] transition-colors ${
                    layer.review_status === r.id
                      ? r.cls
                      : "border-border text-muted-foreground hover:text-foreground"
                  }`}
                >
                  {r.label}
                </button>
              ))}
            </div>
          </section>
        </div>
      )}
    </aside>
  );
}
